[test]
levels = ["syntax", "javascript", "install", "registration", "instantiation", "execution"]
publish = true

[test.workflows]
cpu = ["smpl_to_bvh_pipeline", "load_camera_traj", "apply_motion_on_character"]
cuda = ["GVHMR", "GVHMR_cameramotion"]

[test.platforms]
platforms = ["linux", "windows", "windows_portable", "windows_desktop", "linux_cuda", "windows_cuda", "windows_portable_cuda", "windows_desktop_cuda"]
