[project]
name = "comfyui-motioncapture"
description = "Warning, uses experimental package `comfy-env` to attempt a one click isolated install. Will download and use pixi package manager. Motion Capture nodes for ComfyUI: SMPL data/retargeting using GVHMR"
version = "0.1.19"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/PozzettiAndrea/ComfyUI-MotionCapture"

[tool.comfy]
PublisherId = "pznodes"
DisplayName = "MotionCapture"
Icon = "https://raw.githubusercontent.com/PozzettiAndrea/ComfyUI-MotionCapture/main/assets/icon.png"
